version: 0.2

phases:
  install:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
  build:
    commands:
      - docker build -t spring-api-gradle .
  post_build:
    commands:
      - echo '[{"name":"TestContainer","imageUri":"588738588574.dkr.ecr.us-east-1.amazonaws.com/spring-api-gradle:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '*/'
  discard-paths: no
